sonar.projectKey=qr_gen
sonar.projectName=qr_gen
sonar.sourceEncoding=UTF-8

sonar.sources=gateway,qr-service,frontend
sonar.tests=gateway,qr-service
sonar.test.inclusions=gateway/test_*.py,qr-service/test_*.py
sonar.exclusions=**/__pycache__/**,**/*.pyc,frontend/nginx.conf

sonar.python.version=3.11
sonar.python.coverage.reportPaths=gateway/coverage.xml,qr-service/coverage.xml
